# Generated by Django 6.0.7 on 2026-07-19 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('mobile_shop', 'Mobile Shop'), ('clothing', 'Clothing'), ('pharmacy', 'Pharmacy')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
